name: cd workflow

on:
  push:
    branches:
      - master

jobs:
  log-trial:
    runs-on: ubuntu-latest
    steps:
      - echo "cd hello world"

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU setup
        uses: docker/setup-qemu-action@v1
      - name: docker build setup
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: image build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ivanauliaa/go-hello:latest
