name: ci workflow

on:
  pull_request:
    branches:
      - master

jobs:
  log-trial:
    runs-on: ubuntu-latest
    steps:
      - echo "cd hello world"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: go test -v ./...
