version: '3.7'

services:
  db:
    container_name: "simple_gdm_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.DockerFile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "sample_user"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: "simple_gdm_api"
    build:
      context: .
      dockerfile: api.DockerFile
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - .:/app/

networks:
  default:

volumes:
  mysql_data:

